#!/bin/bash

echo "========================================"
echo "Mini DFS Status Check"
echo "========================================"
echo ""
echo "Base URL: http://localhost:8080 (Naming Service)"
echo ""

echo "========================================"
echo "[1] Naming Service Health"
echo "========================================"
curl -s http://localhost:8080/health || echo "❌ Naming Service is DOWN"
echo ""
echo ""

echo "========================================"
echo "[2] Storage Nodes Status (with Latency)"
echo "========================================"
curl -s http://localhost:8080/nodes || echo "❌ Cannot connect"
echo ""
echo ""

echo "========================================"
echo "[3] Real-time Node Health Check"
echo "========================================"
curl -s http://localhost:8080/nodes/check || echo "❌ Cannot connect"
echo ""
echo ""

echo "========================================"
echo "[4] Files in System"
echo "========================================"
curl -s http://localhost:8080/files || echo "❌ Cannot connect"
echo ""
echo ""

echo "========================================"
echo "[5] Replication Queue"
echo "========================================"
curl -s http://localhost:8080/replication-queue || echo "❌ Cannot connect"
echo ""
echo ""

echo "========================================"
echo "Quick Commands:"
echo "========================================"
echo "Upload:   curl -X POST http://localhost:8080/upload -F 'file=@test.txt'"
echo "Download: curl -O -J http://localhost:8080/download/{FILE_KEY}"
echo "Delete:   curl -X DELETE http://localhost:8080/files/{FILE_KEY}"
echo "Recovery: curl -X POST http://localhost:8080/nodes/node-2/recover"
echo ""
